  
name: aml-register-model

on:
  repository_dispatch:
    types: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check variables
        run: |
          echo "hellooo heree"
