name: CI
on:
  repository_dispatch:
    types: [containerregistry-imagepushed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check variables
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.data) }}
      run: |
          echo  "${{ toJson(github.event.client_payload.data.eventType) }}"
#     - name: Set Context for Azure Kubernetes Cluster using azure/aks-set-context@v1 action
#       uses: azure/aks-set-context@v1
#       with:
#         creds: '${{ secrets.AZURE_CREDENTIALS }}'
#         cluster-name: k8clustertest1
#         resource-group: acrtest
    
#     - uses: Azure/k8s-create-secret@v1
#       with:
#         container-registry-url: acrtest22.azurecr.io
#         container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
#         container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#         secret-name: demo-k8s-secret

#     - uses: azure/k8s-bake@v1
#       with:
#         renderEngine: 'helm2'
#         helmChart: './charts/'
#         overrideFiles: './charts/values.yaml'
#         overrides: |     
#           image.repository: ${{ env.repo_name }}
#           image.tag: ${{ env.repo_version }}
#         releaseName: test
#       id: bake

#     - uses: Azure/k8s-deploy@v1
#       with:
#         manifests: ${{ steps.bake.outputs.manifestsBundle }}
#         images: |
#           ${{ env.image_name }}
#         imagepullsecrets: |
#           demo-k8s-secret
