name: CI
on:
  repository_dispatch:
    types: [containerregistry-imagepushed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check variables
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: |
          echo "::set-env name=repo_name::${{ secrets.REGISTRY_LOGIN_SERVER }}.${{ github.event.client_payload.data.target.repository }}"
          echo "::set-env name=repo_version::${{ github.event.client_payload.data.target.tag }}"
          echo "::set-env name=image_name::${{ secrets.REGISTRY_LOGIN_SERVER }}.${{ github.event.client_payload.data.target.repository }}:${{ github.event.client_payload.data.target.tag }}"
          
    - name: Check variables
      run: |
        echo "${{ env.repo_name }}"
        echo "${{ env.repo_version }}"
        echo ""${{ env.image_name }}"    
