on: [push]
name: Linux_Container_Workflow 

jobs:
    build-and-deploy: 
        runs-on: ubuntu-latest 
        steps: 
        # checkout the repo 
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2
                  
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - run: |
            docker login acrbmwniv2zczfvu.azurecr.io --username aaa6b529-1b46-4d30-882e-8f17e150935c --password Dc_RRESmVl3JdAnLfuYe3bP1h-FNArif5L
            docker pull houssemdocker/angular-app:latest
            docker tag houssemdocker/angular-app:latest acrbmwniv2zczfvu.azurecr.io/my-app6:v1
            docker push acrbmwniv2zczfvu.azurecr.io/my-app6:v1
