on: [pull_request]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2
          
        - name: Create Event Subscription
          id: azure_eventgridsubscriber
          uses: mlopstemplates/azure_eventgridsubscriber@master
          with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            events_to_subscribe: |
                Microsoft.ContainerRegistry.ImagePushed
            provider_type: "Microsoft.ContainerRegistry/registries/acrtest22"
            resource_group: "acrtest"
            pattoken: ${{secrets.PATTOKEN}}
