on: [pull_request]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        - run: |
            cd Docker
            docker build -t abcd221:v1 .
            
            
