on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - run: |
            cd Docker
            docker build -t abcd221:v1 .
            
            
